---
- name: line insert before
  hosts: user-server
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: false
  tasks:
     - name: line insert before
       lineinfile: 
         path: /home/ansible/host
         regexp: '^hostname='
         line: hostname=secure
