---
- name: remove package
  hosts: user-server
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: false
  tasks:
     - name: remove package
       apt:
        name: curl
        state: absent
                     
