---
- name: stop service
  hosts: user-server
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: false
  tasks:
     - name: service stop
       service:
        name: cron
        state: started
                     
